name: Bug report
description: Report a bug in the module
labels: ['Class: bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      description: Describe the exact problem.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Describe how to reproduce the problem
      placeholder: A clear and concise list of steps on how to reproduce the problem or code to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe the expected behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: 'Any other additional context you''d like to add'
      placeholder: Add any other context or screenshots about the problem here.
